name: Auto-merge pull requests

on:
  workflow_call:
    inputs:
      excluded-dependencies:
        type: string
        required: false
        default: ""
        description: Comma-separated list of dependencies to exclude from auto-merging

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    if: >
      contains(fromJSON('["dependabot[bot]", "pre-commit-ci[bot]"]'), github.event.pull_request.user.login)
      && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Disable auto-merge
        if: github.event.pull_request.auto_merge.enabled_by == 'github-actions[bot]'
        run: gh pr merge --disable-auto "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check changed files
        if: github.event.pull_request.commits == 1 && github.event.pull_request.head.user.login == 'pre-commit-ci[bot]'
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const changedFiles = response.data.map(file => file.filename);

            if (changedFiles.length !== 1 || changedFiles[0] !== '.pre-commit-config.yaml') {
              core.setFailed(
                `Unexpected files modified:\n${changedFiles.join('\n')}`
              );
            }

      - name: Wait for pre-commit.ci
        if: github.event.pull_request.commits == 1 && github.event.pull_request.user.login == 'pre-commit-ci[bot]'
        uses: actions/github-script@v7
        with:
          script: |
            const { setTimeout } = require('node:timers/promises');

            const MAX_ATTEMPTS = 12;
            const INTERVAL = 10_000;
            const STATUS_NAME = 'pre-commit.ci - pr';

            async function waitForStatus() {
              for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
                const { data } = await github.rest.repos.getCombinedStatusForRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: context.payload.pull_request.head.sha,
                });

                const status = data.statuses.find(
                  status => status.context === STATUS_NAME,
                );

                if (!status) {
                  console.log(`Waiting for ${STATUS_NAME}...`);
                  await setTimeout(INTERVAL);
                  continue;
                }

                if (status.state === 'success') {
                  console.log(`${STATUS_NAME} check passed!`);
                  return;
                } else if (status.state === 'pending') {
                  console.log(`Waiting for ${STATUS_NAME}...`);
                  await setTimeout(INTERVAL);
                  continue;
                } else {
                  throw new Error(`${STATUS_NAME} check failed with status ${status.state}`);
                }
              }

              throw new Error(`Timeout waiting for ${STATUS_NAME}`);
            }

            await waitForStatus();

      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        uses: dependabot/fetch-metadata@v2

      - name: Check for excluded dependencies
        id: check-dependencies
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const excludedDependencies = '${{ inputs.excluded-dependencies }}'.split(',');
            const dependencyNames = '${{ steps.dependabot-metadata.outputs.dependency-names }}'.split(',');
            return excludedDependencies.some((dependency) => dependencyNames.includes(dependency));

      - name: Enable auto-merge
        if: >
          github.event.pull_request.commits == 1
          && (
            github.event.pull_request.user.login != 'dependabot[bot]'
            || (
              steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'
              && steps.check-dependencies.outputs.result == 'false'
            )
          )
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
